### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by RyanWalker277** [InnogeeksOrganization/InnohacksWebsite#7]
- [x] Timeline 
- [x] Add social media links to the footer
- [x] Sponsor section enhancement
- [ ] Prizes enhancement
- [x] Restore Video section to be the same as past year's
- [ ] Add workshop section
- [ ] Update dates in About Innohacks
- [ ] Fix Dates in Schedule Outline
- [ ] Update Prize pool: 10 lakh TBI + 40,000/- 5ire.
- [ ] Include a "Our Mini-event" section (MySphere card and Programming Pathshala card).
- [ ] Include 5ire Sponsor track.
- [ ] Add the organizing team, judges, and speakers with photos.

**Comment by Anshul-13J** [comment]
- [ ] Update dates in About Innohacks
- [ ] Fix Dates in Schedule Outline
- [ ] Update Prize pool: 10 lakh TBI + 40,000/- 5ire.
- [ ] Include a "Our Mini-event" section (MySphere card and Programming Pathshala card).
- [ ] Include 5ire Sponsor track.
- [ ] Add the organizing team, judges, and speakers with photos.
